# Generated by Django 3.1.3 on 2022-01-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aluno_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
